apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 5000          # The port you want to expose
      targetPort: 5000     # The port the worker container listens on
  type: ClusterIP          # Internal Kubernetes load balancing
