apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: shso9201/demucs-worker:latest
        env:
        - name: MINIO_HOST
          value: "minio-proj.minio-ns.svc.cluster.local:9000"  # The MinIO service hostname in Kubernetes
        - name: MINIO_ACCESS_KEY
          value: "rootuser"   # Replace with your MinIO access key
        - name: MINIO_SECRET_KEY
          value: "rootpass123"   # Replace with your MinIO secret key
        - name: REDIS_HOST
          value: "redis"  # This should match the name of the Redis service
        # resources:
        #   requests:
        #     memory: "0.5Gi"
        #   limits:
        #     memory: "1Gi"